#!/bin/sh

branch=$(git rev-parse --symbolic --abbrev-ref HEAD)
tree=$(git rev-parse --show-toplevel)
values_dir=$tree/Jump/res/values/

if [ "$branch" == "internal-master" ]
then
  echo $tree
  echo `pwd`

  echo \<\?xml version=\"1.0\" encoding=\"utf-8\" \?\> > jr_git_describe.xml
  echo \<resources\> >> jr_git_describe.xml
  echo \ \ \ \ \<string name=\"jr_git_describe\"\>`git describe --always`\</string\> >> jr_git_describe.xml
  echo \</resources\> >> jr_git_describe.xml

  if [ -d $values_dir ]
  then
    mv jr_git_describe.xml $values_dir
    git add $values_dir
  fi
fi
